### ISSUE TITLE
Server on Linux does not run.

### ISSUE THREAD

**Issue by gzcwnk** [LunaPixelStudios/Prominence#125]
### Describe the Bug

steven@minecraft01:~/prom2$ sh start.sh
start.sh: 8: [[: not found
start.sh: 13: source: not found
start.sh: 63: Syntax error: redirection unexpected
steven@minecraft01:~/prom2$

### Reproduction Steps

1.
2.
3.
...

Download, unzip and ?

### Operating System

Debian  11.7

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Prominence_II_FABRIC_Server_Pack_v0.7.0

### Optifine

I used Optifine

### Other Mods

none

**Comment by gzcwnk** [comment]
steven@minecraft01:~/prom2$ java --version
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Debian-1deb11u1, mixed mode, sharing)
steven@minecraft01:~/prom2$

**Comment by gzcwnk** [comment]
readme missing?

**Comment by gzcwnk** [comment]
use bash....

Now I get a modmenu missing.

8><---
[11:42:40] [main/INFO]: Fix: add [add:modmenu 1 ([(-∞,∞)])], remove [], replace []
[11:42:40] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Install modmenu, any version.
Unmet dependency listing:
         - Mod 'Forge Config Screens' (forgeconfigscreens) 8.0.2 requires any version of modmenu, which is missing!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-launcher.jar:0.11.2]

Exiting...
Press any key to continuesteven@minecraft01:~/prom2$

**Comment by dfinlay2** [comment]
Same issue here.  Install menumod in the log

**Comment by nvb-uy** [comment]
Install the modmenu mod
