### ISSUE TITLE
[P2 Fabric] [Server] Invalid character in resource location provided by FTB Quests Config Data

### ISSUE THREAD

**Issue by TigerWalts** [LunaPixelStudios/Prominence#179]
### Describe the Bug

Dedicated server crashes on start due to the resource location for an icon in FTB Quests config data containing invalid characters:

```
Description: Exception in server tick loop

net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: prominent:textures/text/THE_BEGINNING.png
	at net.minecraft.class_2960.method_45137(class_2960.java:252)
	at net.minecraft.class_2960.<init>(class_2960.java:47)
	at net.minecraft.class_2960.<init>(class_2960.java:51)
	at net.minecraft.class_2960.<init>(class_2960.java:56)
	at dev.ftb.mods.ftblibrary.icon.Icon.getIcon0(Icon.java:202)
	at dev.ftb.mods.ftblibrary.icon.Icon.getIcon(Icon.java:130)
	at dev.ftb.mods.ftbquests.quest.ChapterImage.readData(ChapterImage.java:152)
	at dev.ftb.mods.ftbquests.quest.Chapter.readData(Chapter.java:210)
	at dev.ftb.mods.ftbquests.quest.BaseQuestFile.readDataFull(BaseQuestFile.java:675)
	at dev.ftb.mods.ftbquests.quest.ServerQuestFile.load(ServerQuestFile.java:74)
	at dev.ftb.mods.ftbquests.FTBQuestsEventHandler.serverStarted(FTBQuestsEventHandler.java:81)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at jdk.proxy2/jdk.proxy2.$Proxy169.stateChanged(Unknown Source)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$9(EventHandlerImpl.java:65)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$cmf000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:7342)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

`config/ftbquests/quests/chapters/main_story.snbt` 119 - 130
```snbt
		{
			click: ""
			corner: false
			dev: false
			height: 1.0d
			hover: [ ]
			image: "prominent:textures/text/THE_BEGINNING.png"
			rotation: 0.0d
			width: 8.06060606060606d
			x: -7.5d
			y: -8.5d
		}
```

Changing it to all lower case stops the crashing.

Crash not observed on the client due to either the error being caught and handled or a client-only mod 'fixing' bad resource locations. Optifine is known to do this, there may be another mod that does this.

### Crash Report or Log

N/A

### Operating System

N/A

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

Prominence II Fabric 1.3.0hf

### Optifine

No

**Comment by TigerWalts** [comment]
Corrected in v1.3.1
