### ISSUE TITLE
Unable to start server for Prominence II v1.4.0hf FABRIC

### ISSUE THREAD

**Issue by SniketTheLlama** [LunaPixelStudios/Prominence#244]
### Describe the Bug

To begin, I found on my own I needed to go in the properties of the Start.PS1 file and check the box to "Unblock". Once the script ran, I typed "true" when prompted. I then had to relaunch the script for it to get started past the EULA. It then came to "Fabric is not available for Minecraft 1.20.1, Fabric 0.14.23" and stopped.

### Reproduction Steps

1.Launch v1.4.0hf script "Start.ps1" after accepting EULA
2.Let it finish "Running Fabric checks and setup..."
3.
...

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

1.4.0hf

### Optifine

No

### Other Mods

No

**Comment by SniketTheLlama** [comment]
Update. I didn't type "I agree" as the script had asked. I typed "true". I am getting a new error when launching which looks related to Java. I am trying a new Java version now.

**Comment by SniketTheLlama** [comment]
Uninstalled Java and reinstalled. Now back to original error in this ticket.

**Comment by SniketTheLlama** [comment]
Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71)
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
Caused by: java.lang.RuntimeException: Error invoking MC server bundler: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor.process(BundlerProcessor.java:102)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:175)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	... 1 more
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor$1.loadClass(BundlerProcessor.java:65)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor.process(BundlerProcessor.java:85)
	... 7 more

**Comment by SniketTheLlama** [comment]
Looks like I needed to install JDK 17, not JDK 21, or Java SE 8.

**Comment by SniketTheLlama** [comment]
Need to install JDK 17
