### ISSUE TITLE
server crash on boot

### ISSUE THREAD

**Issue by gzcwnk** [LunaPixelStudios/Prominence#257]
end of last.log,

8><-----
[17:58:28] [nioEventLoopGroup-2-1/WARN]: An exception was thrown by gg.lunapixel.luna.e4mc_integration.QuiclimeHandler$$Lambda$22673/0x00007f280e89ee60.operationComplete()
io.netty.incubator.codec.quic.QuicClosedChannelException: null
        at io.netty.incubator.codec.quic.QuicheQuicChannel.failPendingConnectPromise(QuicheQuicChannel.java:406) ~[Luna-FABRIC-MC1.19.X-1.0.1.jar:?]
        at io.netty.incubator.codec.quic.QuicheQuicChannel.doClose(QuicheQuicChannel.java:571) ~[Luna-FABRIC-MC1.19.X-1.0.1.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:754) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:731) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.incubator.codec.quic.QuicheQuicChannel.forceClose(QuicheQuicChannel.java:419) ~[Luna-FABRIC-MC1.19.X-1.0.1.jar:?]
        at io.netty.incubator.codec.quic.QuicheQuicCodec.handlerRemoved(QuicheQuicCodec.java:95) ~[Luna-FABRIC-MC1.19.X-1.0.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:876) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:844) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:836) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:46) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1392) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:198) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:184) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:821) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:821) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
=====

server then exits

**Comment by gzcwnk** [comment]
client seems OK but server will not run

**Comment by gzcwnk** [comment]
I have atm9 running on the std port. I tried incrementing this mod server port and it didnt work.

**Comment by nvb-uy** [comment]
remove the luna mod from your server
