### ISSUE TITLE
Server Crashing on boot

### ISSUE THREAD

**Issue by AlexM2202** [LunaPixelStudios/Prominence#263]
### Describe the Bug

When I tried to run the server inside of crafty controller (my linux server client) I encountered this Minecraft error

[main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Mod §ebetterfpsdist§r requires §6minecraft§r §o1.18 or above, and below 1.19§r
§7Currently, §6minecraft§r§7 is §o1.20.1,
	Mod §et_and_t§r requires §6cristellib§r §o1.0.0 or above§r
§7Currently, §6cristellib§r§7 is §o§nnot installed,
	Mod §elootintegrations§r requires §6minecraft§r §o1.18 or above, and below 1.19§r
§7Currently, §6minecraft§r§7 is §o1.20.1,
	Mod §esmoothchunk§r requires §6minecraft§r §o1.17 or above, and below 1.19§r
§7Currently, §6minecraft§r§7 is §o1.20.1
]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:149) ~[fmlcore-1.20.1-47.2.1.jar%23698!/:?] {}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.2.1-universal.jar%23702!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23697!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.1.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.1.jar%2369!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

### Reproduction Steps

1.
2.
3.
...

### Operating System

Ubuntu 22.04

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

Server Pack v1.4.0

### Optifine

No

**Comment by LynxarA-Coding** [comment]
Same, it is related to Cristellib. It works in singleplayer, but is not visible by server in multiplayer. It occurs not only in Prominence. If I find a solution, I will post it here. If you see no following message, that means I didn't find any :(
